kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: nginx
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #Requests 500 MiB of storage
  storageClassName: local-storage
