kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager-roleBinding
  namespace: apache

subjects:
- kind: User
  name: apache-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: apache-manager  # Assign this manager-role to apache-user
    apiGroup: rbac.authorization.k8s.io
